import { useCallback, useEffect, useState } from 'react'
import useEmblaCarousel from 'embla-carousel-react'
import { ArrowLeft, ArrowRight, Maximize2 } from 'lucide-react'
import Lightbox from 'yet-another-react-lightbox'
import Zoom from 'yet-another-react-lightbox/plugins/zoom'
import Counter from 'yet-another-react-lightbox/plugins/counter'
import 'yet-another-react-lightbox/styles.css'
import 'yet-another-react-lightbox/plugins/counter.css'

// Every source image has a sibling .webp generated by `pnpm images`.
const toWebp = (src) => src.replace(/\.(jpg|jpeg|png)$/i, '.webp')

/**
 * Screenshot viewer. Embla for swipe and keyboard, yet-another-react-lightbox
 * for full-size viewing. Click any shot to enlarge.
 */
export default function Shots({ images, name, aspect = 'aspect-[16/9]' }) {
  const [emblaRef, embla] = useEmblaCarousel({ loop: images.length > 1, align: 'start' })
  const [selected, setSelected] = useState(0)
  const [lightbox, setLightbox] = useState(-1)

  const onSelect = useCallback(() => {
    if (embla) setSelected(embla.selectedScrollSnap())
  }, [embla])

  useEffect(() => {
    if (!embla) return undefined
    onSelect()
    embla.on('select', onSelect)
    embla.on('reInit', onSelect)
    return () => {
      embla.off('select', onSelect)
      embla.off('reInit', onSelect)
    }
  }, [embla, onSelect])

  if (!images?.length) return null

  const many = images.length > 1

  return (
    <div className="flex flex-col gap-3">
      <div className="shot group">
        <div className="overflow-hidden" ref={emblaRef}>
          <div className="flex">
            {images.map((src, i) => (
              <div key={src} className="min-w-0 flex-[0_0_100%]">
                <button
                  type="button"
                  onClick={() => setLightbox(i)}
                  aria-label={`Enlarge ${name} screenshot ${i + 1} of ${images.length}`}
                  className={`block w-full ${aspect} cursor-zoom-in`}
                >
                  <picture>
                    <source type="image/webp" srcSet={toWebp(src)} />
                    <img
                      src={src}
                      alt={`${name} screenshot ${i + 1}`}
                      loading={i === 0 ? 'eager' : 'lazy'}
                      decoding="async"
                      className="w-full h-full object-contain"
                    />
                  </picture>
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Enlarge affordance */}
        <div className="pointer-events-none absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity">
          <span className="flex items-center gap-1.5 text-[11px] text-ink bg-black/70 backdrop-blur px-2.5 py-1.5 rounded-sm">
            <Maximize2 size={11} aria-hidden="true" />
            Enlarge
          </span>
        </div>
      </div>

      {many && (
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-1.5">
            {images.map((src, i) => (
              <button
                key={src}
                type="button"
                onClick={() => embla?.scrollTo(i)}
                aria-label={`Go to screenshot ${i + 1}`}
                aria-current={i === selected}
                className={`h-[3px] rounded-full transition-all duration-200 ${
                  i === selected ? 'w-6 bg-accent' : 'w-2.5 bg-hair-strong hover:bg-ink-faint'
                }`}
              />
            ))}
          </div>

          {/* No "03 / 13" counter: the dot strip above already shows both
              position and total. */}
          <div className="flex items-center gap-1">
            <button
              type="button"
              onClick={() => embla?.scrollPrev()}
              aria-label={`Previous ${name} screenshot`}
              className="w-8 h-8 grid place-items-center rounded-sm border border-hair text-ink-soft hover:text-ink hover:border-hair-strong active:translate-y-px transition-all"
            >
              <ArrowLeft size={14} />
            </button>
            <button
              type="button"
              onClick={() => embla?.scrollNext()}
              aria-label={`Next ${name} screenshot`}
              className="w-8 h-8 grid place-items-center rounded-sm border border-hair text-ink-soft hover:text-ink hover:border-hair-strong active:translate-y-px transition-all"
            >
              <ArrowRight size={14} />
            </button>
          </div>
        </div>
      )}

      <Lightbox
        open={lightbox >= 0}
        index={lightbox}
        close={() => setLightbox(-1)}
        slides={images.map((src) => ({ src }))}
        plugins={[Zoom, Counter]}
        carousel={{ finite: !many }}
        controller={{ closeOnBackdropClick: true }}
        zoom={{ maxZoomPixelRatio: 3 }}
        styles={{ container: { backgroundColor: 'rgba(6,8,11,0.96)' } }}
      />
    </div>
  )
}
